"""Route registration — imports each module and calls its init_app(app)."""

from routes import (
    admin,
    auth_routes,
    batch,
    bi,
    claims,
    clientes,
    compras_dia,
    compras_rapido,
    compras_transfers,
    consulta_producto,
    converter,
    core,
    cuentas,
    dashboard,
    descuentos_base,
    docs_pendientes,
    home_cards,
    inferencia,
    informes,
    invoices,
    laboratorios,
    modulo_packs,
    modulos_import,
    obras_sociales,
    obras_sociales_catalogo,
    observer,
    observer_sync,
    ofertas_import,
    partners,
    plantillas,
    procesos,
    productos,
    productos_pendientes,
    providers,
    purchase,
    recetas_scan,
    vademecum,
)
from routes import help as help_module

_modules = [
    auth_routes,
    observer,
    observer_sync,
    admin,
    home_cards,
    core,
    providers,
    laboratorios,
    invoices,
    converter,
    claims,
    purchase,
    modulo_packs,
    modulos_import,
    productos,
    cuentas,
    dashboard,
    docs_pendientes,
    batch,
    vademecum,
    obras_sociales,
    obras_sociales_catalogo,
    clientes,
    compras_dia,
    compras_rapido,
    compras_transfers,
    consulta_producto,
    descuentos_base,
    procesos,
    productos_pendientes,
    partners,
    plantillas,
    ofertas_import,
    help_module,
    inferencia,
    informes,
    bi,
    recetas_scan,
]


def register_routes(app):
    for mod in _modules:
        mod.init_app(app)
